### ISSUE TITLE
Selenium/Watir with dokku-chrome

### ISSUE THREAD

**Issue by jiax83** [lazyatom/dokku-chrome#1]
Probably a long-shot question... the Readme isn't clear on how `dokku-chrome` is _not_ supposed to be used. So I'd like to clarify.

I have a Rails web app running inside dokku, the web app has `webdrivers` and `watir` (which basically is built on top of Selenium) in Gemfile. When the web app runs, it tries to open a headless Chrome browser to read a web page. But even after installing `dokku-chrome`, the app would throw this error: "_Failed to find Chrome binary_". So is `dokku-chrome` supposed to provide a Chrome binary inside dokku? If not, any idea how a Chrome binary could be installed in dokku?

Appreciate any pointer.

**Comment by lazyatom** [comment]
This plugin produces a browser _service_, rather than making a browser binary actually available to your application. As mentioned near the top of the README, you interact with it using an API, so from your application you'd send an HTTP request to this service to do things like render screenshots or generate PDFs.

I think for your use case, you have a couple of options. If you want a chrome binary to be accessible directly by your Rails application, it needs to be included in your application Docker image, so you'll need to install it as part of your Rails application build. Look into the https://github.com/dokku-community/dokku-apt plugin for how to install arbitrary packages as part of an app build.

Alternatively, it looks like it _is_ possible to interact with the Chrome service as a backend to Selenium. I haven't used it like this, but the documentation on browserless.io has examples that you might be able to adapt for Watir: https://docs.browserless.io/docs/selenium-library.html
https://docs.browserless.io/docs/capybara.html

Between those two, you may be able to figure out how to tell Watir/Selenium to use the webdriver endpoint being exposed by the service (the root URL is exposed by default as a `CHROME_URL` environment variable to any linked apps).

Hope that helps!

**Comment by jiax83** [comment]
Thank you @lazyatom for the response! I'm looking into dokku-apt for now.
